# .github/workflows/telegram.yml

name: Telegram Notification

on:
  pull_request:
    branches: ["master"]
    types: [opened]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Notification on PR
        if: github.event_name == 'pull_request'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          message: |
            Recent PR by ${{ github.actor }} from ${{ github.head_ref }} to ${{ github.base_ref }}

            PR Title : ${{ github.event.pull_request.title }}

            PR link: ${{ github.event.pull_request.html_url }}

            Please review @${{ secrets.OWNER }}
